[[constraint]]
  name = "github.com/fatih/color"
  version = "1.7.0"

[[constraint]]
  branch = "master"
  name = "github.com/ghetzel/argonaut"

[[constraint]]
  name = "github.com/ghetzel/cli"
  version = "1.16.0"

[[override]]
  name = "github.com/ghetzel/diecast"
  version = "1.8.5"

[[override]]
  name = "github.com/ghetzel/friendscript"
  branch = "master"

[[constraint]]
  name = "github.com/ghetzel/go-stockutil"
  version = ">=1.5.36"

[[constraint]]
  name = "github.com/gobwas/glob"
  version = "0.2.3"

[[constraint]]
  name = "github.com/gorilla/websocket"
  version = "1.2.0"

[[constraint]]
  name = "github.com/husobee/vestigo"
  version = "1.1.0"

[[constraint]]
  name = "github.com/mafredri/cdp"
  version = "0.18.2"

[[constraint]]
  name = "github.com/mcuadros/go-defaults"
  branch = "master"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/go-ps"

[[constraint]]
  name = "github.com/phayes/freeport"
  version = "1.0.2"

[[constraint]]
  name = "github.com/urfave/negroni"
  version = "0.3.0"

[prune]
  go-tests = true
  unused-packages = true
